import Foundation
import Testing

@testable import MakeDevaCore
@testable import MakeDevaCLI

/// Resolves `samples/` for parity tests: env override, then walk up from this file toward repo root.
private func resolveParitySamplesDirectory(file: String = #filePath) -> String {
    if let env = ProcessInfo.processInfo.environment["MAKEDEVA_SAMPLES_PATH"],
       FileManager.default.fileExists(atPath: "\(env)/LT/expected")
    {
        return env
    }

    var url = URL(fileURLWithPath: file).deletingLastPathComponent()
    for _ in 0..<14 {
        let samples = url.appendingPathComponent("samples")
        let marker = samples.appendingPathComponent("LT/expected")
        if FileManager.default.fileExists(atPath: marker.path) {
            return samples.path
        }
        guard url.path != "/" else { break }
        url.deleteLastPathComponent()
    }

    let cwd = FileManager.default.currentDirectoryPath
    let cwdCandidates = [
        "\(cwd)/samples",
        URL(fileURLWithPath: cwd).deletingLastPathComponent().appendingPathComponent("samples").path,
        URL(fileURLWithPath: cwd).deletingLastPathComponent().deletingLastPathComponent()
            .appendingPathComponent("samples").path,
    ]
    for path in cwdCandidates where FileManager.default.fileExists(atPath: "\(path)/LT/expected") {
        return path
    }

    return cwdCandidates[0]
}

/// Functional parity tests that compare Swift output against expected C output.
/// These tests ensure byte-for-byte compatibility with the original C makedeva utility.
///
/// Test files are located in:
/// - samples/LT/ - Lithuanian translation samples (33 files)
/// - samples/HU/ - Hungarian translation samples (18 files)
///
/// Expected outputs are generated by the C utility and stored in:
/// - samples/LT/expected/
/// - samples/HU/expected/
struct FunctionalParityTests {
    private static var samplesPath: String { resolveParitySamplesDirectory() }
    
    // MARK: - LT (Lithuanian) Sample Tests
    
    @Test("LTS301XT functional parity")
    func testLTS301XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS301XT")
    }
    
    @Test("LTS302XT functional parity")
    func testLTS302XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS302XT")
    }
    
    @Test("LTS303XT functional parity")
    func testLTS303XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS303XT")
    }
    
    @Test("LTS304XT functional parity")
    func testLTS304XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS304XT")
    }
    
    @Test("LTS305XT functional parity")
    func testLTS305XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS305XT")
    }
    
    @Test("LTS306XT functional parity")
    func testLTS306XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS306XT")
    }
    
    @Test("LTS307XT functional parity")
    func testLTS307XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS307XT")
    }
    
    @Test("LTS308XT functional parity")
    func testLTS308XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS308XT")
    }
    
    @Test("LTS309XT functional parity")
    func testLTS309XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS309XT")
    }
    
    @Test("LTS310XT functional parity")
    func testLTS310XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS310XT")
    }
    
    @Test("LTS311XT functional parity")
    func testLTS311XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS311XT")
    }
    
    @Test("LTS312XT functional parity")
    func testLTS312XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS312XT")
    }
    
    @Test("LTS313XT functional parity")
    func testLTS313XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS313XT")
    }
    
    @Test("LTS314XT functional parity")
    func testLTS314XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS314XT")
    }
    
    @Test("LTS315XT functional parity")
    func testLTS315XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS315XT")
    }
    
    @Test("LTS316XT functional parity")
    func testLTS316XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS316XT")
    }
    
    @Test("LTS317XT functional parity")
    func testLTS317XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS317XT")
    }
    
    @Test("LTS318XT functional parity")
    func testLTS318XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS318XT")
    }
    
    @Test("LTS319XT functional parity")
    func testLTS319XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS319XT")
    }
    
    @Test("LTS320XT functional parity")
    func testLTS320XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS320XT")
    }
    
    @Test("LTS321XT functional parity")
    func testLTS321XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS321XT")
    }
    
    @Test("LTS322XT functional parity")
    func testLTS322XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS322XT")
    }
    
    @Test("LTS323XT functional parity")
    func testLTS323XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS323XT")
    }
    
    @Test("LTS324XT functional parity")
    func testLTS324XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS324XT")
    }
    
    @Test("LTS325XT functional parity")
    func testLTS325XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS325XT")
    }
    
    @Test("LTS326XT functional parity")
    func testLTS326XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS326XT")
    }
    
    @Test("LTS327XT functional parity")
    func testLTS327XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS327XT")
    }
    
    @Test("LTS328XT functional parity")
    func testLTS328XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS328XT")
    }
    
    @Test("LTS329XT functional parity")
    func testLTS329XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS329XT")
    }
    
    @Test("LTS330XT functional parity")
    func testLTS330XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS330XT")
    }
    
    @Test("LTS331XT functional parity")
    func testLTS331XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS331XT")
    }
    
    @Test("LTS332XT functional parity")
    func testLTS332XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS332XT")
    }
    
    @Test("LTS333XT functional parity")
    func testLTS333XT() async throws {
        try await runParityTest(directory: "LT", filePrefix: "LTS333XT")
    }
    
    // MARK: - HU (Hungarian) Sample Tests
    
    @Test("HUBG01XT functional parity")
    func testHUBG01XT() async throws {
        try await runParityTest(directory: "HU", filePrefix: "HUBG01XT")
    }
    
    @Test("HUBG02XT functional parity")
    func testHUBG02XT() async throws {
        try await runParityTest(directory: "HU", filePrefix: "HUBG02XT")
    }
    
    @Test("HUBG03XT functional parity")
    func testHUBG03XT() async throws {
        try await runParityTest(directory: "HU", filePrefix: "HUBG03XT")
    }
    
    @Test("HUBG04XT functional parity")
    func testHUBG04XT() async throws {
        try await runParityTest(directory: "HU", filePrefix: "HUBG04XT")
    }
    
    @Test("HUBG05XT functional parity")
    func testHUBG05XT() async throws {
        try await runParityTest(directory: "HU", filePrefix: "HUBG05XT")
    }
    
    @Test("HUBG06XT functional parity")
    func testHUBG06XT() async throws {
        try await runParityTest(directory: "HU", filePrefix: "HUBG06XT")
    }
    
    @Test("HUBG07XT functional parity")
    func testHUBG07XT() async throws {
        try await runParityTest(directory: "HU", filePrefix: "HUBG07XT")
    }
    
    @Test("HUBG08XT functional parity")
    func testHUBG08XT() async throws {
        try await runParityTest(directory: "HU", filePrefix: "HUBG08XT")
    }
    
    @Test("HUBG09XT functional parity")
    func testHUBG09XT() async throws {
        try await runParityTest(directory: "HU", filePrefix: "HUBG09XT")
    }
    
    @Test("HUBG10XT functional parity")
    func testHUBG10XT() async throws {
        try await runParityTest(directory: "HU", filePrefix: "HUBG10XT")
    }
    
    @Test("HUBG11XT functional parity")
    func testHUBG11XT() async throws {
        try await runParityTest(directory: "HU", filePrefix: "HUBG11XT")
    }
    
    @Test("HUBG12XT functional parity")
    func testHUBG12XT() async throws {
        try await runParityTest(directory: "HU", filePrefix: "HUBG12XT")
    }
    
    @Test("HUBG13XT functional parity")
    func testHUBG13XT() async throws {
        try await runParityTest(directory: "HU", filePrefix: "HUBG13XT")
    }
    
    @Test("HUBG14XT functional parity")
    func testHUBG14XT() async throws {
        try await runParityTest(directory: "HU", filePrefix: "HUBG14XT")
    }
    
    @Test("HUBG15XT functional parity")
    func testHUBG15XT() async throws {
        try await runParityTest(directory: "HU", filePrefix: "HUBG15XT")
    }
    
    @Test("HUBG16XT functional parity")
    func testHUBG16XT() async throws {
        try await runParityTest(directory: "HU", filePrefix: "HUBG16XT")
    }
    
    @Test("HUBG17XT functional parity")
    func testHUBG17XT() async throws {
        try await runParityTest(directory: "HU", filePrefix: "HUBG17XT")
    }
    
    @Test("HUBG18XT functional parity")
    func testHUBG18XT() async throws {
        try await runParityTest(directory: "HU", filePrefix: "HUBG18XT")
    }
    
    // MARK: - Test Helper
    
    /// Run a parity test for a specific sample file
    /// - Parameters:
    ///   - directory: The subdirectory under samples/ (e.g., "LT" or "HU")
    ///   - filePrefix: The file prefix (e.g., "LTS301XT")
    private func runParityTest(directory: String, filePrefix: String) async throws {
        let samplesPath = Self.samplesPath
        let dirPath = "\(samplesPath)/\(directory)"
        let expectedPath = "\(dirPath)/expected"
        
        // Find the input file (may have different extensions like .H33, .H67, etc.)
        let inputFile = try findFile(in: dirPath, withPrefix: filePrefix)
        let inputFileName = (inputFile as NSString).lastPathComponent
        let expectedFile = "\(expectedPath)/\(inputFileName).expected"
        
        // Verify files exist
        guard FileManager.default.fileExists(atPath: inputFile) else {
            Issue.record(Comment(rawValue: "Input file not found: \(inputFile)"))
            return
        }
        guard FileManager.default.fileExists(atPath: expectedFile) else {
            Issue.record(Comment(rawValue: "Expected output file not found: \(expectedFile)"))
            return
        }
        
        // Create temporary output file
        let tempDir = FileManager.default.temporaryDirectory
        let outputFile = tempDir.appendingPathComponent("\(filePrefix)_swift_output.txt").path
        
        // Run Swift conversion with default options
        do {
            let options = CLIOptions()
            try FileProcessor.processFile(input: inputFile, output: outputFile, options: options)
        } catch {
            Issue.record(Comment(rawValue: "Swift conversion failed: \(error)"))
            return
        }
        
        // Compare outputs
        let expectedData = try Data(contentsOf: URL(fileURLWithPath: expectedFile))
        let actualData = try Data(contentsOf: URL(fileURLWithPath: outputFile))
        
        if expectedData != actualData {
            // Find first difference for debugging
            let (lineNum, expectedLine, actualLine) = findFirstDifference(
                expected: expectedData, actual: actualData)
            
            Issue.record(Comment(rawValue: """
                Output mismatch for \(filePrefix):
                First difference at line \(lineNum):
                  Expected: \(expectedLine)
                  Actual:   \(actualLine)
                Expected size: \(expectedData.count) bytes
                Actual size: \(actualData.count) bytes
                """))
        }
        
        // Clean up temp file
        try? FileManager.default.removeItem(atPath: outputFile)
        
        #expect(expectedData == actualData, "Output should match expected C output for \(filePrefix)")
    }
    
    /// Find a file in a directory with a given prefix
    private func findFile(in directory: String, withPrefix prefix: String) throws -> String {
        let fm = FileManager.default
        let contents = try fm.contentsOfDirectory(atPath: directory).sorted()
        for name in contents where name != ".DS_Store" {
            let full = "\(directory)/\(name)"
            var isDir: ObjCBool = false
            guard fm.fileExists(atPath: full, isDirectory: &isDir), !isDir.boolValue else { continue }
            if name.hasPrefix(prefix) { return full }
        }
        throw NSError(
            domain: "FunctionalParityTests", code: 1,
            userInfo: [NSLocalizedDescriptionKey: "No file found with prefix \(prefix) in \(directory)"])
    }
    
    /// Find the first line that differs between expected and actual output
    private func findFirstDifference(expected: Data, actual: Data) -> (lineNum: Int, expectedLine: String, actualLine: String) {
        let expectedLines = String(data: expected, encoding: .isoLatin1)?.components(separatedBy: .newlines) ?? []
        let actualLines = String(data: actual, encoding: .isoLatin1)?.components(separatedBy: .newlines) ?? []
        
        let maxLines = max(expectedLines.count, actualLines.count)
        for i in 0..<maxLines {
            let expectedLine = i < expectedLines.count ? expectedLines[i] : "<missing>"
            let actualLine = i < actualLines.count ? actualLines[i] : "<missing>"
            
            if expectedLine != actualLine {
                // Truncate long lines for readability
                let truncatedExpected = expectedLine.count > 80 ? String(expectedLine.prefix(80)) + "..." : expectedLine
                let truncatedActual = actualLine.count > 80 ? String(actualLine.prefix(80)) + "..." : actualLine
                return (i + 1, truncatedExpected, truncatedActual)
            }
        }
        
        return (0, "", "")
    }
}

// MARK: - Batch Test for CI/CD

/// A single test that runs all parity checks - useful for quick CI validation
struct FunctionalParityBatchTests {
    
    @Test("All samples pass functional parity")
    func testAllSamplesParity() async throws {
        var failures: [String] = []
        let samplesPath = resolveParitySamplesDirectory()

        // Test all LT files
        let ltFiles = ["LTS301XT", "LTS302XT", "LTS303XT", "LTS304XT", "LTS305XT",
                       "LTS306XT", "LTS307XT", "LTS308XT", "LTS309XT", "LTS310XT",
                       "LTS311XT", "LTS312XT", "LTS313XT", "LTS314XT", "LTS315XT",
                       "LTS316XT", "LTS317XT", "LTS318XT", "LTS319XT", "LTS320XT",
                       "LTS321XT", "LTS322XT", "LTS323XT", "LTS324XT", "LTS325XT",
                       "LTS326XT", "LTS327XT", "LTS328XT", "LTS329XT", "LTS330XT",
                       "LTS331XT", "LTS332XT", "LTS333XT"]

        // Test all HU files
        let huFiles = ["HUBG01XT", "HUBG02XT", "HUBG03XT", "HUBG04XT", "HUBG05XT",
                       "HUBG06XT", "HUBG07XT", "HUBG08XT", "HUBG09XT", "HUBG10XT",
                       "HUBG11XT", "HUBG12XT", "HUBG13XT", "HUBG14XT", "HUBG15XT",
                       "HUBG16XT", "HUBG17XT", "HUBG18XT"]

        let allJobs: [(dir: String, prefix: String)] =
            ltFiles.map { ("LT", $0) } + huFiles.map { ("HU", $0) }

        let maxConcurrent = 6
        var iterator = allJobs.makeIterator()
        await withTaskGroup(of: String?.self) { group in
            func addNext() {
                if let job = iterator.next() {
                    group.addTask {
                        FunctionalParityBatchTests.runQuickParityCheck(
                            samplesPath: samplesPath, directory: job.dir, filePrefix: job.prefix)
                    }
                }
            }
            for _ in 0..<min(maxConcurrent, allJobs.count) { addNext() }
            while let failure = await group.next() {
                if let failure { failures.append(failure) }
                addNext()
            }
        }
        
        if !failures.isEmpty {
            let failureMessage = "Parity failures:\n" + failures.joined(separator: "\n")
            Issue.record(Comment(rawValue: failureMessage))
        }
        
        #expect(failures.isEmpty, "All \(ltFiles.count + huFiles.count) sample files should pass parity check")
        print("✅ All \(ltFiles.count + huFiles.count) sample files passed parity check")
    }
    
    /// Quick parity check that returns `"id: reason"` or nil on success
    private nonisolated static func runQuickParityCheck(
        samplesPath: String, directory: String, filePrefix: String
    ) -> String? {
        let dirPath = "\(samplesPath)/\(directory)"
        let expectedPath = "\(dirPath)/expected"
        
        // Find input file
        guard let inputFile = try? findFile(in: dirPath, withPrefix: filePrefix) else {
            return "\(filePrefix): input file not found"
        }
        
        let inputFileName = (inputFile as NSString).lastPathComponent
        let expectedFile = "\(expectedPath)/\(inputFileName).expected"
        
        guard FileManager.default.fileExists(atPath: expectedFile) else {
            return "\(filePrefix): expected file not found"
        }
        
        // Create temp output
        let tempDir = FileManager.default.temporaryDirectory
        let outputFile = tempDir.appendingPathComponent("\(filePrefix)_test.txt").path
        
        // Run conversion with default options
        do {
            let options = CLIOptions()
            try FileProcessor.processFile(input: inputFile, output: outputFile, options: options)
        } catch {
            return "\(filePrefix): conversion error: \(error)"
        }
        
        // Compare
        guard let expectedData = try? Data(contentsOf: URL(fileURLWithPath: expectedFile)),
              let actualData = try? Data(contentsOf: URL(fileURLWithPath: outputFile)) else {
            return "\(filePrefix): failed to read output files"
        }
        
        try? FileManager.default.removeItem(atPath: outputFile)
        
        if expectedData != actualData {
            return
                "\(filePrefix): output mismatch (\(expectedData.count) vs \(actualData.count) bytes)"
        }

        return nil
    }

    private nonisolated static func findFile(in directory: String, withPrefix prefix: String) throws
        -> String
    {
        let fm = FileManager.default
        let contents = try fm.contentsOfDirectory(atPath: directory).sorted()
        for name in contents where name != ".DS_Store" {
            let full = "\(directory)/\(name)"
            var isDir: ObjCBool = false
            guard fm.fileExists(atPath: full, isDirectory: &isDir), !isDir.boolValue else { continue }
            if name.hasPrefix(prefix) { return full }
        }
        throw NSError(domain: "Test", code: 1, userInfo: nil)
    }
}
